inherit: "config/base.yaml"

use_calib: False
single_thread: True
dataset:
  subsample: 2

multidataset:
  datasets:
    - id: "7-scenes"
      path: '/home/rtx4090/Desktop/tmax/johnk/Multicam-MASt3R-SLAM/datasets/7-scenes/chess' 
      camera_id: 0

# Specify which camera is used as the reference for synchronization.
  reference_camera_id: 0
  number_of_camera: 1