inherit: "config/base.yaml"
multidataset:
  datasets:
    - id: "webcam"
      type: "webcam"
      camera_id: 0

    - id: "iphone"
      type: "iphone"
      path: "http://143.248.162.217:4747/video"
      camera_id: 1

    # - id: "android"
    #   type: "android"
    #   path: "http://143.248.163.221:8080/video"
    #   camera_id: 2


  urls:
    iphone_path: "http://143.248.162.217:4747/video"
    android_path: "http://143.248.163.221:8080/video"




# Specify which camera is used as the reference for synchronization.
  reference_camera_id: 0
  number_of_camera: 2