inherit: "config/base.yaml"
multidataset:
  datasets:
    - id: "youtube"
      path: "https://youtu.be/hXD8itTKdY0?si=CHw3krHQDCkykPue"
      camera_id: 0

    
# Specify which camera is used as the reference for synchronization.
  reference_camera_id: 0 #TODO..
  number_of_camera: 1

dataset:
  subsample: 1  
  img_downsample: 1
  center_principle_point: True


